version: "3.8"

services:
  db:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "8079:8079"

  server1:
    build: .
    command: "server --port=8080"
    depends_on:
      - db
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    command: "server --port=8080"
    depends_on:
      - db
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    command: "server --port=8080"
    depends_on:
      - db
    networks:
      - servers
    ports:
      - "8082:8080"

  balancer:
    build: .
    command: "lb"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - servers
    ports:
      - "8090:8090"

networks:
  servers:
